site_name: three_d
site_description: Upload and download 3d models
repo_url: https://github.com/vsmaxim/three-d
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/vsmaxim">vsmaxim</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
